# Generated by Django 4.2 on 2024-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serivces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('content1', models.TextField(default='test')),
                ('status1', models.BooleanField(default=False)),
                ('created_at1', models.DateTimeField(auto_now_add=True)),
                ('updated_at1', models.DateTimeField(auto_now=True)),
                ('name2', models.CharField(max_length=100)),
                ('content2', models.TextField(default='test')),
                ('status2', models.BooleanField(default=False)),
                ('created_at2', models.DateTimeField(auto_now_add=True)),
                ('updated_at2', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
