# Generated by Django 4.2 on 2024-08-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serivces',
            new_name='serivce',
        ),
    ]
