# Generated by Django 4.2 on 2024-08-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rename_serivces_serivce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serivce',
            old_name='status1',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='serivce',
            name='status2',
        ),
    ]
