# Generated by Django 4.2 on 2024-08-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_rename_status1_serivce_status_remove_serivce_status2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serivce',
            new_name='service',
        ),
    ]
