# Generated by Django 4.2 on 2024-08-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_rename_serivce_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
