# Generated by Django 4.2 on 2024-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content1',
            field=models.TextField(default='برای سرویس هااین فیلد را پر کنید'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content2',
            field=models.TextField(default='برای سرویس های ویژه این فیلد را پر کنید.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name1',
            field=models.CharField(default='برای سرویس هااین فیلد را پر کنید', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='name2',
            field=models.CharField(default='برای سرویس های ویژه این فیلد را پر کنید', max_length=100),
        ),
    ]
