# Generated by Django 4.2 on 2024-08-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
