# Generated by Django 4.2 on 2024-08-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_service_status1_service_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
