# Generated by Django 4.2 on 2024-08-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_remove_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status1',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status2',
        ),
    ]
