# Generated by Django 4.2 on 2024-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_rename_status1_service_status_remove_service_status2'),
    ]

    operations = [
        migrations.CreateModel(
            name='so',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(default='برای سرویس های ویژه این فیلد را پر کنید', max_length=100)),
                ('content2', models.TextField(default='برای سرویس های ویژه این فیلد را پر کنید.')),
                ('created_at2', models.DateTimeField(auto_now_add=True)),
                ('updated_at2', models.DateTimeField(auto_now=True)),
                ('status2', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at2',
        ),
    ]
