# Generated by Django 4.2 on 2024-08-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_so_remove_service_content2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='so',
            old_name='status2',
            new_name='status',
        ),
    ]
