# Generated by Django 4.2 on 2024-08-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_pricing_property_services_skills_specialservices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='questions',
            new_name='name',
        ),
    ]
