# Generated by Django 4.2 on 2024-08-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='image',
            field=models.ImageField(default='static\\img\\hero-bg-light.webp', upload_to='trainers'),
        ),
    ]
