# Generated by Django 4.2 on 2024-08-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_alter_trainers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='content',
            field=models.TextField(default='test ask'),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(default='test service'),
        ),
        migrations.AlterField(
            model_name='specialservices',
            name='content',
            field=models.TextField(default='no content'),
        ),
    ]
